name: Deploy to Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install vue cli
        run: yarn global add @vue/cli

      - name: 🗃 Cache Yarn
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          # De cache wordt alleen naderhand opgeslagen als yarn.lock veranderd is
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          # De cache wordt opgehaald als os hetzelfde is (altijd)
          restore-keys: ${{ runner.os }}-yarn-
        
      - name: Install yarn dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable
        
      - name: Run build
        run: yarn run build

      - uses: crazy-max/ghaction-github-pages@v2.2.0
        if: github.ref == 'refs/heads/main'
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
